/**
 * Who makes VOLO, why it exists, and how to reach whoever broke it.
 *
 * A tool that asks people to believe "your load order is not uploaded" has to
 * be willing to say who is making that claim. This page is the answer to that,
 * and to the reasonable question of why a stranger's sorting rules should be
 * trusted over your own judgement.
 */

import { Link } from 'wouter';
import { ArrowRight } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { useStore } from '@/lib/store';

const REPO = 'https://github.com/Moonie8t7/VOLO';

export default function AboutPage() {
  const { masterlist } = useStore();
  const modCount = masterlist?.plugins.length;

  return (
    <div className="p-8 overflow-auto min-h-screen bg-gradient-to-br from-background via-background to-card">
      <div className="max-w-3xl mx-auto space-y-10">
        <header>
          <h1 className="text-4xl font-display font-bold text-gradient-bg3">
            About VOLO
          </h1>
          <p className="text-muted-foreground mt-2 font-body">
            Who built this, and why you might reasonably not trust it yet.
          </p>
        </header>

        <section className="space-y-4 font-body leading-relaxed">
          <h2 className="font-display text-2xl font-bold">Who</h2>
          <p>
            VOLO is made by{' '}
            <a href={REPO} target="_blank" rel="noreferrer" className="underline hover:text-foreground">
              Moonie8t7
            </a>
            , one person, as a community project. It is not affiliated with
            Larian Studios, Nexus Mods or mod.io, and nobody pays for placement
            in it. Every line of it is public: if you want to know what it does
            with your file, the answer is readable rather than promised.
          </p>
          <p>
            The load order dividers that give the sort its structure are the
            work of{' '}
            <a
              href="https://forums.nexusmods.com/profile/106303673-astralities/"
              target="_blank"
              rel="noreferrer"
              className="underline hover:text-foreground"
            >
              Astralities
            </a>
            , who made them for their own playthroughs and gave permission for
            them to be used and adapted here.
          </p>
        </section>

        <section className="space-y-4 font-body leading-relaxed">
          <h2 className="font-display text-2xl font-bold">Why</h2>
          <p>
            Baldur's Gate 3 has no LOOT. Load order advice lives in comment
            sections and pinned posts, it contradicts itself, and most of it is
            somebody's memory of what worked once. Meanwhile thousands of people
            have working orders sitting in their mod manager, which is real
            evidence that nobody was collecting.
          </p>
          <p>
            So VOLO collects it. The rules come from orders people played on,
            not from opinion, and where the evidence runs out the tool says so
            rather than inventing a placement. That is the whole idea.
          </p>
        </section>

        <section className="space-y-4 font-body leading-relaxed">
          <h2 className="font-display text-2xl font-bold">How it is built</h2>
          <p>
            Submitted orders go into a public corpus. A script reads them,
            works out which category each mod belongs to and where categories
            sit relative to each other, and writes a masterlist of{' '}
            {modCount ? modCount.toLocaleString() : 'around three thousand'} mods.
            The site downloads that file and does the sorting in your browser.
            Nothing about your own list is sent anywhere unless you choose to
            submit it.
          </p>
          <p>
            The masterlist is generated by a program, not written by hand, and
            the program is not clever: it counts things. Where a placement came
            from a count rather than from a person, the interface says so, and
            you can{' '}
            <Link href="/measured" className="underline hover:text-foreground">
              read what happened when we measured it
            </Link>
            .
          </p>
        </section>

        <section className="space-y-4 font-body leading-relaxed">
          <h2 className="font-display text-2xl font-bold">
            Reasons to be sceptical
          </h2>
          <p>
            The corpus is small. Nine working orders is not a lot of evidence,
            and it is the thing holding quality back rather than the sorting
            itself. Several sensible-sounding improvements have measured worse
            than doing nothing.
          </p>
          <p>
            Hundreds of mods have no category at all, and they wait at the end
            of the order rather than being guessed at. VOLO is a starting point
            you check, not an authority. If it puts something in the wrong
            place, you are probably right and it is probably wrong.
          </p>
        </section>

        <section className="space-y-4 font-body leading-relaxed">
          <h2 className="font-display text-2xl font-bold">Getting in touch</h2>
          <p>
            Bugs, wrong placements and disagreements all go to{' '}
            <a
              href={`${REPO}/issues`}
              target="_blank"
              rel="noreferrer"
              className="underline hover:text-foreground"
            >
              the issue tracker
            </a>
            . If a mod is filed wrongly, the most useful thing you can send is
            the order you actually played on, because that corrects the evidence
            rather than one entry.
          </p>
          <div className="flex flex-wrap gap-3 pt-2">
            <Link href="/submit">
              <Button>
                Submit a load order
                <ArrowRight className="ml-2 h-4 w-4" aria-hidden="true" />
              </Button>
            </Link>
            <a href={REPO} target="_blank" rel="noreferrer">
              <Button variant="outline">View the source</Button>
            </a>
          </div>
        </section>
      </div>
    </div>
  );
}
