#!/usr/bin/env node
/**
 * Writes public/sitemap.xml with a `lastmod` taken from git.
 *
 *   node scripts/build-sitemap.mjs
 *
 * A hand-typed lastmod is worse than none: it freezes on the day someone
 * remembered to edit it, and then every page claims a freshness it does not
 * have. Google treats dates that do not track real change as a bad signal, so
 * each route's date comes from the last commit that touched the files behind
 * it. No git, no dates, rather than invented ones.
 *
 * Routes that need a load order already in the session are left out; they carry
 * noindex in client/src/lib/head.ts instead.
 */

import fs from 'fs';
import { execFileSync } from 'child_process';

const SITE = 'https://volobg3.com';

/**
 * Each route with the sources that decide when it last changed. The landing
 * page is listed against the whole client because its copy summarises the tool.
 */
const ROUTES = [
  {
    path: '/',
    priority: '1.0',
    sources: ['client/src/pages/LandingPage.tsx', 'client/index.html'],
  },
  {
    path: '/import',
    priority: '0.9',
    sources: ['client/src/pages/ImportPage.tsx', 'client/src/lib/parser.ts'],
  },
  {
    path: '/masterlist',
    priority: '0.8',
    changefreq: 'daily',
    sources: ['client/src/pages/MasterlistPage.tsx', 'masterlist/bg3-masterlist.json'],
  },
  {
    path: '/measured',
    priority: '0.8',
    sources: ['client/src/pages/MeasuredPage.tsx', 'docs/decisions.md'],
  },
  {
    path: '/about',
    priority: '0.7',
    sources: ['client/src/pages/AboutPage.tsx'],
  },
  {
    path: '/submit',
    priority: '0.7',
    sources: ['client/src/pages/SubmitPage.tsx'],
  },
  {
    path: '/donations',
    priority: '0.3',
    sources: ['client/src/pages/DonationsPage.tsx'],
  },
];

/** Commit date of the newest change to any of these files, as YYYY-MM-DD. */
function lastModified(sources) {
  const dates = sources
    .filter(file => fs.existsSync(file))
    .map(file => {
      try {
        return execFileSync('git', ['log', '-1', '--format=%cs', '--', file], {
          encoding: 'utf8',
        }).trim();
      } catch {
        return '';
      }
    })
    .filter(Boolean);
  return dates.sort().pop() ?? null;
}

const entries = ROUTES.map(route => {
  const lastmod = lastModified(route.sources);
  const lines = [
    '  <url>',
    `    <loc>${SITE}${route.path}</loc>`,
    lastmod ? `    <lastmod>${lastmod}</lastmod>` : null,
    route.changefreq ? `    <changefreq>${route.changefreq}</changefreq>` : null,
    `    <priority>${route.priority}</priority>`,
    '  </url>',
  ].filter(Boolean);
  return { xml: lines.join('\n'), lastmod, path: route.path };
});

const xml = [
  '<?xml version="1.0" encoding="UTF-8"?>',
  '<!-- Generated by scripts/build-sitemap.mjs. Do not edit by hand. -->',
  '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
  ...entries.map(e => e.xml),
  '</urlset>',
  '',
].join('\n');

fs.writeFileSync('public/sitemap.xml', xml);

console.log(`wrote public/sitemap.xml with ${entries.length} routes`);
for (const e of entries) console.log(`  ${e.path.padEnd(12)} ${e.lastmod ?? 'no date'}`);
